SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY
FROM ITEM_TREE AS T
JOIN ITEM_INFO AS P ON P.ITEM_ID = T.PARENT_ITEM_ID
JOIN ITEM_INFO AS I ON I.ITEM_ID = T.ITEM_ID
WHERE P.RARITY = 'RARE'
ORDER BY ITEM_ID DESC